apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::133354030153:role/eksctl-Backend-cluster-nodegroup-s-NodeInstanceRole-CrG9NauRuqPu
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::133354030153:user/amplify-dev
      username: admin
      groups:
        - system:masters
