apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 133354030153.dkr.ecr.us-east-1.amazonaws.com/backend
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: APP_DOMAIN
              value: "poc-api.autovrse.app"
            - name: WEB_DOMAIN
              value: "https://poc.autovrse-training.com/"         # ✅ Update this to your actual frontend domain
            - name: APP_JWT_KEY
              value: "test-jwt-secret"                   # ✅ Use a real secure secret in production
            - name: JWT_KEY_FOR_INVITE
              value: "invite-jwt-secret"
            - name: MONGODB_USER
              value: admin
            - name: MONGODB_PASSWORD
              value: admin
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DB_NAME
              value: vrse

        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage

      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
