apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80            # service port (used by Ingress and curl)
      targetPort: 3000    # internal container port of your backend app
