apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        # ✅ Backend Container
        - name: backend-container
          image: tarkesh/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_USER
              value: "admin"
            - name: MONGODB_PASSWORD
              value: "admin"
            - name: MONGODB_HOST
              value: "mongodb-service"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DB_NAME
              value: "vrseBuilder"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"




---
# ✅ Service for Backend
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer


