apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80           # External service port (used by Ingress or curl)
      targetPort: 3000   # Internal container port of your backend app
  type: ClusterIP        # ✅ Use ClusterIP when using Ingress for external access
