apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        # ✅ Backend Container
        - name: backend-container
          image: tarkesh/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_USER
              value: "admin"
            - name: MONGODB_PASSWORD
              value: "admin"
            - name: MONGODB_HOST
              value: "localhost"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DB_NAME
              value: "vrseBuilder"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

        # ✅ MongoDB Container
        - name: mongodb-container
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "admin"
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db

      # ✅ Volume for MongoDB data persistence
      volumes:
        - name: mongo-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
