apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-no-delete-binding
  namespace: default
subjects:
- kind: User
  name: regular-user        # Replace with the Kubernetes username of the non-admin user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: mongodb-no-delete-role
  apiGroup: rbac.authorization.k8s.io
